Repository SyneRBI/PETRIC, pull requests merged in 2024-09, with the labels that each got.

#97 fix conda environment.yml
  .github/workflows/run.yml
Labels: bug

#102 Mediso NEMA IQ data
  SIRF_data_preparation/Mediso_NEMA_IQ/README.md
  SIRF_data_preparation/Mediso_NEMA_IQ/prepare.py
  SIRF_data_preparation/data_QC.py
  SIRF_data_preparation/dataset_settings.py
  SIRF_data_preparation/plot_BSREM_metrics.py
  SIRF_data_preparation/run_OSEM.py
  petric.py
Labels: data

#104 TensorBoard: add sagittal slice
  petric.py
Labels: enhancement

#107 update instructions for creating a new dataset
  .gitignore
  SIRF_data_preparation/README.md
  SIRF_data_preparation/Siemens_mMR_ACR/README.md
  SIRF_data_preparation/Siemens_mMR_ACR/prepare.py
  SIRF_data_preparation/Siemens_mMR_NEMA_IQ/prepare_mMR_NEMA_IQ_data.py
  SIRF_data_preparation/create_initial_images.py
  SIRF_data_preparation/data_QC.py
Labels: documentation, data

#91 prepare for evaluation phase and run more data
  petric.py
Labels: enhancement, data

#116 add FOV_mask to Dataset
  petric.py
Labels: enhancement
