Repository SyneRBI/PETRIC, pull requests merged in 2024-07, with the labels that each got.

#32 petric: get_data fixes
  .gitignore
  petric.py
Labels: enhancement

#35 ISTA
  main.py
  main_ISTA.py
Labels: enhancement

#39 update ISTA step-size
  main_ISTA.py
Labels: enhancement

#48 add QC for reference image and VOIs
  SIRF_data_preparation/data_QC.py
Labels: enhancement

#52 more options for data_QC
  SIRF_data_preparation/data_QC.py
Labels: enhancement, data

#49 Use CUDA RDP if it exists
  petric.py
Labels: enhancement

#53 fix objectives.csv
  SIRF_data_preparation/data_QC.py
  petric.py
Labels: bug

#55 replace namedtuple => dataclass
  petric.py
Labels: enhancement

#54 main_OSEM
  main_OSEM.py
Labels: documentation, enhancement

#56 drop symlink
  .github/workflows/run.yml
  README.md
  main.py
Labels: documentation, enhancement

#57 metrics: standalone `log()`
  main_OSEM.py
  petric.py
Labels: enhancement

#60 SaveIters: flush csv each row
  petric.py
Labels: enhancement

#61 data_QC VOI improvements
  SIRF_data_preparation/data_QC.py
Labels: enhancement, data

#59 callbacks with custom interval
  petric.py
Labels: enhancement

#65 Evaluation utilities
  SIRF_data_preparation/README.md
  SIRF_data_preparation/data_QC.py
  SIRF_data_preparation/evaluation_utilities.py
  petric.py
Labels: enhancement

#67 metrics: exclude callback time
  petric.py
Labels: enhancement

#68 metrics: pass criterion
  SIRF_data_preparation/evaluation_utilities.py
Labels: enhancement

#75 raise & document runtime
  README.md
  petric.py
Labels: documentation, enhancement

#78 preliminary utility for evolution of metrics
  SIRF_data_preparation/create_initial_images.py
  SIRF_data_preparation/data_QC.py
  SIRF_data_preparation/data_utilities.py
  SIRF_data_preparation/plot_BSREM_metrics.py
  SIRF_data_preparation/prepare_mMR_NEMA_IQ_data.py
  main_OSEM.py
Labels: enhancement

#76 docs: common pip/conda packages
  README.md
Labels: documentation

#80 expose data.path
  petric.py
Labels: enhancement, participant, data
