Repository SyneRBI/PETRIC, pull requests merged in 2024-08, with the labels that each got.

#81 docker dev instructions
  README.md
Labels: documentation, participant

#83 docs: leaderboard config & metrics runtime
  README.md
Labels: documentation

#88 Siemens mMR_ACR updates
  .gitignore
  SIRF_data_preparation/Siemens_mMR_ACR/README.md
  SIRF_data_preparation/Siemens_mMR_ACR/VOI_prep.py
  SIRF_data_preparation/Siemens_mMR_ACR/download.py
  SIRF_data_preparation/Siemens_mMR_ACR/prepare.py
  SIRF_data_preparation/Siemens_mMR_ACR/register_mumap.py
  SIRF_data_preparation/Siemens_mMR_NEMA_IQ/Siemens_mMR_NEMA_VOIs.py
  SIRF_data_preparation/create_initial_images.py
  SIRF_data_preparation/data_utilities.py
  SIRF_data_preparation/dataset_settings.py
  SIRF_data_preparation/run_BSREM.py
Labels: data
